#!/bin/bash

# this script performs post-processing on the documentation generated by the staatic plugin.
# that plugin does not find references to the old (wordpress-site) domain for *.xsl files,
# so we need to fix those references here.

set -ue
DOCS_DIR="docs"

echo "Starting post-processing of generated files in '${DOCS_DIR}'..."

wp_domain="$(cat docs/*.xsl | grep -oP '(https?://[^/]+)/.*sitemap.xml' | cut -d/ -f1-3 | head -n 1)"
echo "- looking for references to '${wp_domain}'"

xsl_pattern='(https?://[^/]+)/.*\.xsl'
static_domain="$(
    cat docs/sitemap.xml \
    | grep -oP 'xml-stylesheet.*?'"${xsl_pattern}" \
    | grep -oP "${xsl_pattern}" \
    | cut -d/ -f1-3 \
    | head -n 1
)"
echo "- replacing with references to '${static_domain}'"

# replace occurrences of the wordpress domain with the static domain in all text files
# we filter to *.xsl because that's all we expect to need; we could safely remove it to check all text files
# "exec grep" finds only text files; "exec sed" edits the files in place without any backup
find "${DOCS_DIR}" -type f -iname "*.xsl" -exec grep -Iq . {} \; -exec sed -i 's|'"${wp_domain}"'|'"${static_domain}"'|g' {} +

echo "Post-processing completed."
